[package]
name = "rasterizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.19.0"
wgpu = { version = "0.12.0", optional = true }
futures = { version = "0.3.21", optional = true }
raw-window-handle = { version = "0.4.2", optional = true }
bytemuck = { version = "1.7.3", features = ["derive"] }

[features]
wgpu_presenter = ["wgpu", "futures", "raw-window-handle"]

[[example]]
name = "lines"
required-features = ["wgpu_presenter"]

[dev-dependencies]
winit = "0.26.1"
